/*
 * out.java
 *
 * Created on May 11, 2017, 9:59 AM
 */

package System;

import DBconnect.DBcon;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  DELL
 */
public class out extends javax.swing.JInternalFrame {

     Connection con = null;
     PreparedStatement pst = null;
     PreparedStatement pt = null;
     ResultSet rs = null;
     ResultSet rss = null;
     
     double subtot=0;
    double grandtot=0;
    
    public out() {
        initComponents();
        
        con = (Connection) DBcon.connect();
        lbldiscount.setText("");
        lblname.setText("");
        lblprice.setText("");
        txtqty.setText("");
        txtsku.setText("");
        lblqty.setText("");
        
        new Thread(new Runnable() {

            public void run() {
               // throw new UnsupportedOperationException("Not supported yet.");
                //meek aniw ain krnn
                
                while(true){
                
                Date d=new Date();
                String date =d.toString();
                String arr[]=date.split(" ");
                String dd=arr[5]+"/"+arr[1]+"/"+arr[2];
                lbldate.setText(dd);
                
                lbltime.setText(arr[3]);
                
                }
                
            }
        }).start();
        
        double x=0;
        x=Math.random()*100000;
        DecimalFormat d1=new DecimalFormat("#");
        int y=Integer.parseInt(d1.format(x));
        String billno="INV"+Integer.toString(y);
        lblbillno.setText(billno);
       
        txtsku.setRequestFocusEnabled(true);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblqty = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsku = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblsub = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbldiscount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblgrand = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblbillno = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblprice = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setTitle("Sell Products");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(1310, 570));
        setMinimumSize(new java.awt.Dimension(1310, 690));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1310, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel7.setText("Grand Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 490, -1, 20));

        lbltime.setText("jLabel8");
        getContentPane().add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 110, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Time");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 70, -1));

        lbldate.setText("jLabel8");
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 140, 20));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("On Hands");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, 30));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Clear All");
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 140, 40));

        lblqty.setText("jLabel13");
        getContentPane().add(lblqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 140, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Qty");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 50, -1));

        txtsku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtskuActionPerformed(evt);
            }
        });
        getContentPane().add(txtsku, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 160, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Bodoni MT", 1, 14));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Print Bill");
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 170, 40));

        lblsub.setFont(new java.awt.Font("Tahoma", 1, 18));
        lblsub.setText("00.00");
        getContentPane().add(lblsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 450, 170, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel16.setText("Sub Total");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, -1, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Price");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 70, -1));

        txtqty.setText("jTextField1");
        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });
        getContentPane().add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 100, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Discount");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 90, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Date");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 70, -1));

        lbldiscount.setText("jLabel15");
        getContentPane().add(lbldiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 140, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Product SKU");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 120, -1));

        lblgrand.setFont(new java.awt.Font("Tahoma", 1, 18));
        lblgrand.setText("00.00");
        getContentPane().add(lblgrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 490, 170, 20));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Name", "Qty", "Price", "Discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(25);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(4).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(50);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 1190, 260));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 80, -1));

        lblbillno.setText("jLabel8");
        getContentPane().add(lblbillno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 120, 20));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Bill#");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 90, 40));

        lblname.setText("jLabel10");
        getContentPane().add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 240, 40));

        lblprice.setText("jLabel12");
        getContentPane().add(lblprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 120, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setMaximumSize(new java.awt.Dimension(1310, 690));
        jLabel8.setMinimumSize(new java.awt.Dimension(1310, 690));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1310, 570));

        setBounds(0, 0, 1310, 575);
    }// </editor-fold>//GEN-END:initComponents

   
private void txtskuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtskuActionPerformed
// TODO add your handling code here:
    try {

        String s=("SELECT i.id,p.name,p.price,p.discount,i.qty FROM product p , inventory i WHERE p.id='"+txtsku.getText()+"' AND i.id = p.id");
        
        pst = (PreparedStatement) con.prepareStatement(s);
        rs = pst.executeQuery(); 
        
        
        
        while(rs.next()){
        
                lblname.setText(rs.getString("name"));
                lblprice.setText(rs.getString("price"));
                lbldiscount.setText(rs.getString("discount"));
                lblqty.setText(rs.getString("qty"));
        }
        
        txtqty.grabFocus();
        
    } catch (Exception e) {
        
        e.printStackTrace();
    }
}//GEN-LAST:event_txtskuActionPerformed

private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed

    
       try {
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        Vector v=new Vector();
        
        v.add(txtsku.getText());
        v.add(lblname.getText());
        v.add(txtqty.getText());
        v.add(lblprice.getText());
        v.add(lbldiscount.getText());
        dtm.addRow(v);
        
        String price=lblprice.getText();
        String qty=txtqty.getText();
        String discount=lbldiscount.getText();
        
        double price1=Double.parseDouble(price);
        double qty1=Double.parseDouble(qty);
        double discount1=Double.parseDouble(discount);
        
        subtot=subtot+(qty1*price1);
        DecimalFormat d1=new DecimalFormat("#.00");
        lblsub.setText(d1.format(subtot));
        
        grandtot=grandtot+((price1*qty1)-discount1);
        lblgrand.setText(d1.format(grandtot));
        
        lbldiscount.setText("");
        lblname.setText("");
        lblprice.setText("");
        txtqty.setText("");
        txtsku.setText("");
        lblqty.setText("");
        
        txtsku.grabFocus();
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
}//GEN-LAST:event_txtqtyActionPerformed

private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
 
    lblsub.setText("00.00");
    lblgrand.setText("00.00");

    for (int x = 0; x < jTable1.getRowCount(); x++) {
        
        try {
            
                String id = (String) jTable1.getValueAt(x, 0);
                String s2 = (String) jTable1.getValueAt(x, 2);
                
                String s1 = ("SELECT qty FROM inventory WHERE id = '"+id+"'");         
                
                pt =     (PreparedStatement) con.prepareStatement(s1);
                ResultSet r = pt.executeQuery();
                
                while(r.next()){
                    
                    String str =  r.getString("qty");
                          
                    int y = Integer.parseInt(str) - Integer.parseInt(s2);
                       
                    if( y>=0 ){
                    
                        String nqty = Integer.toString(y);
                    
                    String s = ("UPDATE inventory SET qty = '"+nqty+"' WHERE id = '"+id+"'");
  
                    pt = (PreparedStatement) con.prepareStatement(s);
                    pt.executeUpdate();
                        
                    }
                    
                    else{
                        String msg = (String) jTable1.getValueAt(x, 1);
                        JOptionPane.showMessageDialog(rootPane, "Not inaf "+msg);
                    }
                }
                
        } catch (Exception e) {
            
            System.out.println(e);
        }
   
    }
    
    removeTableItems();
    
}//GEN-LAST:event_jLabel10MouseClicked

private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        lbldiscount.setText("");
        lblname.setText("");
        lblprice.setText("");
        txtqty.setText("");
        txtsku.setText("");
        lblqty.setText("");
        lblsub.setText("00.00");
        lblgrand.setText("00.00");
        
        removeTableItems();
    
}//GEN-LAST:event_jLabel13MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblbillno;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldiscount;
    private javax.swing.JLabel lblgrand;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblqty;
    private javax.swing.JLabel lblsub;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtsku;
    // End of variables declaration//GEN-END:variables
 private void removeTableItems() {
     
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        
    }

}
