/*
 * User.java
 *
 * Created on May 7, 2017, 3:26 AM
 */

package System;


import DBconnect.DBcon;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  user
 */
public class supplier extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /** Creates new form User */
    public supplier() {
        initComponents();
     
       tableload();
        
        
        txtaddress.setText("");
        txtemail.setText("");
        txtid.setText("");
        txtname.setText("");
        txtnic.setText("");
        txttelno.setText("");
        txtsearch.setText("");
        
        con = DBcon.connect();
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txttelno = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtnic = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable123 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supplier");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("NIC");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, 130, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 70));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Calibri", 1, 90)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Supplier");
        jLabel18.setOpaque(true);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 360, 110));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 250, 30));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 250, 30));

        txttelno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelnoActionPerformed(evt);
            }
        });
        getContentPane().add(txttelno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 260, 30));

        txtemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtemailMouseExited(evt);
            }
        });
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 260, 30));
        getContentPane().add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 260, 30));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1360, 140));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel11.setText("User ID");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText(" Name");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 120, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel13.setText("Address");
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 120, 40));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel15.setText("Contact No");
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 130, 40));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel16.setText("Email");
        jLabel16.setOpaque(true);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 130, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delete");
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 130, 50));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Save");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, 50));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Bodoni MT", 1, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Update");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 130, 50));

        jTable123.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name", "Contact No", "Email", "NIC", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable123.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable123MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable123);
        jTable123.getColumnModel().getColumn(0).setResizable(false);
        jTable123.getColumnModel().getColumn(1).setResizable(false);
        jTable123.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable123.getColumnModel().getColumn(2).setResizable(false);
        jTable123.getColumnModel().getColumn(3).setResizable(false);
        jTable123.getColumnModel().getColumn(4).setResizable(false);
        jTable123.getColumnModel().getColumn(5).setResizable(false);
        jTable123.getColumnModel().getColumn(5).setPreferredWidth(200);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 690, 380));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Search");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 100, 30));

        txtsearch.setText("jTextField1");
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 290, 30));

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane2.setViewportView(txtaddress);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 260, 80));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 750));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1366)/2, (screenSize.height-768)/2, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

private void txtemailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMouseExited
// TODO add your handling code here:
        
}//GEN-LAST:event_txtemailMouseExited

private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed

    txtaddress.grabFocus();
    
}//GEN-LAST:event_txtnameActionPerformed

private void txttelnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelnoActionPerformed

    txtemail.grabFocus();
    
}//GEN-LAST:event_txttelnoActionPerformed

private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed

    txtname.grabFocus();
   
}//GEN-LAST:event_txtidActionPerformed

private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed

    txtnic.grabFocus();
    
}//GEN-LAST:event_txtemailActionPerformed

private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
main m = new main();
    m.setVisible(true);
    this.dispose();
}//GEN-LAST:event_jLabel10MouseClicked

private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    
    validation();
    
    try {
        
        int x=JOptionPane.showConfirmDialog(rootPane, "Do u want to save this record?");
        if(x==0){

            con = DBcon.connect();
            
            String s3 = ("INSERT INTO supplier VALUES('"+txtid.getText()+"','"+txtname.getText()+"','"+txttelno.getText()+"','"+txtaddress.getText()+"','"+txtnic.getText()+"','"+txtemail.getText()+"')");
            
           pst = (PreparedStatement) con.prepareStatement(s3);
           pst.execute();
                       
        txtaddress.setText("");
        txtemail.setText("");
        txtid.setText("");
        txtname.setText("");
        txtnic.setText("");
        txttelno.setText("");
        
        JOptionPane.showMessageDialog(rootPane, "successfully saved");
        }
        else if(x==1){
     
        txtaddress.setText("");
        txtemail.setText("");
        txtid.setText("");
        txtname.setText("");
        txtnic.setText("");
        txttelno.setText("");
        
        }  
        
    } catch (Exception e) {
        
        e.printStackTrace();
    }
    
}//GEN-LAST:event_jLabel5MouseClicked

private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

    
    try {

        
          String  s5 = ("DELETE FROM supplier WHERE id='"+txtid.getText()+"'");
          
           pst = (PreparedStatement) con.prepareStatement(s5);
           pst.executeUpdate();
          
         txtaddress.setText("");
        txtemail.setText("");
        txtid.setText("");
        txtname.setText("");
        txtnic.setText("");
        txttelno.setText("");
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
}//GEN-LAST:event_jLabel1MouseClicked

private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

     validation();
    
    try {
        
        String s2 = ("UPDATE supplier SET phone='"+txttelno.getText()+"',address='"+txtaddress.getText()+"'  WHERE id='"+txtid.getText()+"'");
        
           pst = (PreparedStatement) con.prepareStatement(s2);
           pst.executeUpdate();
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    
}//GEN-LAST:event_jLabel6MouseClicked

private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

}//GEN-LAST:event_jLabel8MouseClicked

private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed

}//GEN-LAST:event_txtsearchActionPerformed

private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
search();
}//GEN-LAST:event_txtsearchKeyPressed

private void jTable123MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable123MouseClicked

    int row = jTable123.getSelectedRow();
    String click = (String) jTable123.getModel().getValueAt(row, 0);
    
    try {
        
        String sql = (" SELECT * FROM supplier WHERE id = '"+click+"' ");
        pst = (PreparedStatement) con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        while(rs.next()){
        
        txtaddress.setText(rs.getString("address"));
        txtemail.setText(rs.getString("email"));
        txtid.setText(rs.getString("id"));
        txtname.setText(rs.getString("name"));
        txtnic.setText(rs.getString("nic"));
        txttelno.setText(rs.getString("phone"));
            
        }
        
        
    } catch (Exception e) {
   
        System.out.println(e);
    }
    
    
}//GEN-LAST:event_jTable123MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier().setVisible(true);
            }
        });
    }
    
    
 
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable123;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txttelno;
    // End of variables declaration//GEN-END:variables

    
    public void validation(){{
       
   //email 
        
    String email=txtemail.getText();
    
    if(!(email.contains("@")))
    {
        JOptionPane.showMessageDialog(rootPane, "plz enter valied email"); 
        
    }
   
    // phone
    
    
    
    //not null
    
    if( txtname.getText().equals("") ){
    
    }
    
    else if(txtaddress.equals("")){
    
        JOptionPane.showMessageDialog(rootPane, "Please input user address ");
        
    }
    
    //NIC
    
    
        
    }}
    
     public void search(){
    
            try {
        
         DefaultTableModel dtm=(DefaultTableModel)jTable123.getModel();
         dtm.setRowCount(0);
            
        con = (Connection) DBcon.connect();
        
        String sql = ("SELECT * FROM supplier where name LIKE '%"+txtsearch.getText()+"%' ");

        pst = (PreparedStatement) con.prepareStatement(sql);
        rs = pst.executeQuery();
        
         while (rs.next()) {                    
                  Object[] rowData={rs.getString("id"),rs.getString("name"),rs.getString("phone"),rs.getString("email"),rs.getString("nic"),rs.getString("address")};
                   dtm.addRow(rowData); 
                }
            
        } catch (Exception e) {
        
        System.out.println(e);
            
        }
    
    } 
     
         public void tableload(){
    
            try {
            
        con = (Connection) DBcon.connect();
        String sql = ("SELECT * FROM inventory i, product p where i.id = p.id");
          DefaultTableModel dtm=(DefaultTableModel) jTable123.getModel();
        pst = (PreparedStatement) con.prepareStatement(sql);
        rs = pst.executeQuery();
        
         while (rs.next()) {                    
                  Object[] rowData={rs.getString("id"),rs.getString("name"),rs.getString("type"),rs.getString("phone"),rs.getString("email"),rs.getString("nic"),rs.getString("address")};
                   dtm.addRow(rowData); 
                }
        
            
        } catch (Exception e) {
        
        System.out.println(e);
            
        }
    
    }
    
}
